name: Build EXE

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: mingw-w64-ucrt-x86_64-gcc zip

      - name: Build
        run: |
          gcc file2c.c -O2 -s -static -o file2c.exe
          zip file2c.zip file2c.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: file2c.zip
