name: Build EXE

on:
  workflow_dispatch:

  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc

      - name: Build
        run: gcc file2c.c -O2 -s -static -o file2c.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: file2c
          path: file2c.exe

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: file2c.exe
